load tempfileWS
n = 4; p = 3;
% number of p-combinations out of n
n_bc = bc(n,p);
% Pascal matrix
pascalM=pascal(n);
% n_bc is the Pascal cell in position (n-p+1,p+1)
n_bc==pascalM(n-p+1,p+1)
% all p-combinations in reverse-colex order generated by lexunrank
% using a loop with rank integers ranging from 0 to bc(n,p)-1
all_recolex = nan(n_bc,p);
for N_lex = 0:n_bc-1
all_recolex(N_lex+1,:) = lexunrank(n,p,N_lex);
end
all_recolex
close all
save tempfileWS